In [1]:
import torch
import numpy as np

### Initializing a Tensor
#### Directly from data

In [ ]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

#### From a Numpy array

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

#### From another tensor

In [5]:
#塞1
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.4474, 0.8363],
        [0.0578, 0.3679]]) 



#### With random or constant values:

In [7]:
shape = (2,3)
rand_tensor = torch.rand(shape)
#ones: 給形狀、ones_like 給tensor
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")


Random Tensor: 
 tensor([[0.3983, 0.8119, 0.5537],
        [0.7378, 0.4116, 0.6082]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



### Attributes of a Tensor

In [8]:
tensor = torch.rand(3,4)

print(f"Shape of a tensor: {tensor.shape}")
print(f"Datatype of a tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of a tensor: torch.Size([3, 4])
Datatype of a tensor: torch.float32
Device tensor is stored on: torch.Size([3, 4])
